version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:latest
    environment:
      DB_SERVER: db
      DB_NAME: prestashopdb
      DB_USER: prestashopusr
      DB_PASSWORD: prestashoppassword
      PS_INSTALL_AUTO: "1"
      PS_DEV_MODE: "0" # Modo de producción
      ADMIN_MAIL: "admin@example.com"
      ADMIN_PASSWD: "adminpassword"
    volumes:
      - prestashop_data:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - nginx

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: prestashopdb
      MYSQL_USER: prestashopusr
      MYSQL_PASSWORD: prestashoppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    depends_on:
      - openssl

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
    networks:
      - frontend

  openssl:
    image: alpine:latest
    volumes:
      - ./certs:/certs
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache openssl && mkdir -p /certs && openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /certs/server.key -out /certs/server.crt -subj '/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=gourmetshop.com'"]
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  prestashop_data:
  db_data:
